import QuestionPage from '@/components/QuestionPage';

const WhatIsSEOROI = () => (
  <QuestionPage
    slug="what-is-seo-roi"
    question="What is the ROI of SEO?"
    shortAnswer="SEO ROI measures the return on investment from organic search traffic compared to costs, typically calculated by tracking revenue generated from organic visitors."
    content={{
      introduction: `SEO ROI (Return on Investment) measures the value generated by your SEO efforts compared to the cost of implementing them. Unlike paid advertising where ROI is more straightforward to calculate, SEO ROI requires attributing value to organic traffic and considering the cumulative, long-term nature of SEO investments.

Understanding SEO ROI is crucial for justifying SEO budgets, comparing SEO to other marketing channels, and making informed decisions about resource allocation. However, calculating it accurately can be challenging because SEO results compound over time and benefit multiple aspects of your business.

The good news is that SEO typically delivers strong ROI compared to other marketing channels. Studies consistently show that organic search drives more revenue than paid search for many businesses, and the cost per acquisition from SEO tends to decrease over time as your site builds authority.`,
      sections: [
        {
          id: 'calculating-seo-roi',
          title: 'How to Calculate SEO ROI',
          content: `Basic SEO ROI formula and considerations:

**Basic ROI Formula:**
ROI = (Revenue from SEO - Cost of SEO) / Cost of SEO × 100

**Example Calculation:**
- Monthly SEO investment: $5,000
- Revenue attributed to organic traffic: $25,000
- ROI = ($25,000 - $5,000) / $5,000 × 100 = 400%

**What to Include in SEO Costs:**
- Agency fees or in-house salaries
- Content creation costs
- Technical SEO tools
- Link building expenses
- Design and development time

**Attributing Revenue to SEO:**
- Track organic traffic conversions in Google Analytics
- Set up goal tracking for leads/sales
- Use UTM parameters for attribution
- Consider assisted conversions (SEO in the path)
- Track phone calls from organic visitors

**Challenges in Measurement:**
- Long time lag between investment and results
- Assisted conversions are hard to value
- Brand awareness benefits are intangible
- Some SEO value is defensive (maintaining position)
- Multi-touch attribution complexity`
        },
        {
          id: 'metrics-to-track',
          title: 'Key ROI Metrics to Track',
          content: `Monitor these metrics to understand SEO performance:

**Traffic Metrics:**
- Organic sessions and users
- Organic traffic growth rate
- Traffic by landing page
- Traffic by target keyword

**Conversion Metrics:**
- Organic conversion rate
- Leads/sales from organic traffic
- Revenue attributed to organic
- Cost per organic acquisition

**Ranking Metrics:**
- Keyword positions over time
- Number of ranking keywords
- Featured snippets captured
- Share of voice vs. competitors

**Value Metrics:**
- Customer lifetime value from organic leads
- Traffic value (what you'd pay in ads)
- Cost per organic acquisition vs. paid

**How to Calculate Traffic Value:**
Estimate what you'd pay for the same traffic via ads:
1. Export organic keywords and their traffic
2. Multiply each by its CPC (from Google Ads)
3. Sum total = estimated traffic value

Example: 10,000 monthly visits × $2 avg CPC = $20,000/month traffic value

**Long-Term Value Considerations:**
- SEO assets appreciate over time
- Content continues ranking for years
- Domain authority compounds
- Brand searches increase with visibility`
        },
        {
          id: 'improving-seo-roi',
          title: 'Strategies to Improve SEO ROI',
          content: `Maximize the return from your SEO investment:

**Focus on High-Intent Keywords:**
- Commercial keywords drive more revenue
- Balance traffic volume with conversion potential
- Target keywords your buyers actually search

**Improve Conversion Rates:**
- Optimize landing pages for organic traffic
- Clear CTAs and user journeys
- Fast page load speeds
- Mobile optimization

**Reduce Acquisition Costs:**
- Build in-house SEO capabilities
- Create efficient content workflows
- Repurpose content across channels
- Focus on high-impact activities

**Extend Content Lifetime:**
- Update existing content regularly
- Build evergreen content that lasts
- Consolidate thin content
- Improve top-performing pages

**Track and Attribute Properly:**
- Implement proper analytics
- Set up goal and conversion tracking
- Consider attribution modeling
- Track offline conversions if applicable

**Benchmarks and Expectations:**
- Average SEO ROI: 275-1,220% (varies by industry)
- Results typically take 6-12 months
- ROI improves over time as authority builds
- First year often shows lower ROI than subsequent years

**When ROI Is Hard to Measure:**
- Brand awareness campaigns
- Very long sales cycles
- Multi-channel customer journeys
- Local foot traffic attribution

In these cases, track leading indicators like rankings, traffic, and engagement while working on better conversion tracking.`
        }
      ]
    }}
    tableOfContents={[
      { id: 'introduction', title: 'Overview' },
      { id: 'calculating-seo-roi', title: 'Calculating ROI' },
      { id: 'metrics-to-track', title: 'Metrics to Track' },
      { id: 'improving-seo-roi', title: 'Improving ROI' },
      { id: 'data-insights', title: 'Data Insights' },
      { id: 'related-questions', title: 'Related Questions' }
    ]}
    chartData={{
      type: 'bar',
      title: 'SEO ROI Over Time',
      data: [
        { name: 'Year 1', value: 150 },
        { name: 'Year 2', value: 350 },
        { name: 'Year 3', value: 500 },
        { name: 'Year 4', value: 680 },
        { name: 'Year 5', value: 800 }
      ]
    }}
    imageUrl="https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop"
    imageAlt="Analytics dashboard showing SEO ROI and revenue metrics"
    relatedQuestions={[
      { slug: 'how-much-does-seo-cost', question: 'How much does SEO cost?' },
      { slug: 'how-long-does-seo-take', question: 'How long does SEO take?' },
      { slug: 'seo-vs-ppc', question: 'SEO vs PPC?' }
    ]}
    relatedTerms={[
      { slug: 'organic-traffic', term: 'Organic Traffic' },
      { slug: 'keyword-research', term: 'Keyword Research' },
      { slug: 'click-through-rate', term: 'Click-Through Rate' }
    ]}
  />
);

export default WhatIsSEOROI;
